# Generated by Django 3.2 on 2021-04-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
